// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBujIYAU6YiX1kd69HqeY9exU1GeCePLkc',
    appId: '1:698957160713:web:fbf7e6080210037430f3d8',
    messagingSenderId: '698957160713',
    projectId: 'ring-sorting-machine',
    authDomain: 'ring-sorting-machine.firebaseapp.com',
    databaseURL: 'https://ring-sorting-machine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ring-sorting-machine.appspot.com',
    measurementId: 'G-LQQ1NG09Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_2lD9jrzlDLcirt35Uvj1ESqJXjV8Y5k',
    appId: '1:698957160713:android:1d6ae01d322a348030f3d8',
    messagingSenderId: '698957160713',
    projectId: 'ring-sorting-machine',
    databaseURL: 'https://ring-sorting-machine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ring-sorting-machine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyjfEQ91roSmcyPtthcyfj9WcagahUSZw',
    appId: '1:698957160713:ios:3fe0311150ac0b0d30f3d8',
    messagingSenderId: '698957160713',
    projectId: 'ring-sorting-machine',
    databaseURL: 'https://ring-sorting-machine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ring-sorting-machine.appspot.com',
    iosClientId: '698957160713-chu31o7rh5jotp85382pisrt7hob8fm2.apps.googleusercontent.com',
    iosBundleId: 'com.autobonics.hydropodHydroponics',
  );
}
