// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZRnQ0MHXxdFRXMqkibTiT4FfUBLpjm50',
    appId: '1:835265270110:web:fecbd78990eacca55effcf',
    messagingSenderId: '835265270110',
    projectId: 'nutmeg-9414e',
    authDomain: 'nutmeg-9414e.firebaseapp.com',
    databaseURL: 'https://nutmeg-9414e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutmeg-9414e.appspot.com',
    measurementId: 'G-BXL92VVQ9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFZnsNGD_vr2oUuKKdxxTCT8v1TLf2TZ4',
    appId: '1:835265270110:android:aab55735bd4ca9ee5effcf',
    messagingSenderId: '835265270110',
    projectId: 'nutmeg-9414e',
    databaseURL: 'https://nutmeg-9414e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutmeg-9414e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU2jfKaaNffDstdnIh9siZPzgaHJ-i3iw',
    appId: '1:835265270110:ios:4e4c5db8186304f75effcf',
    messagingSenderId: '835265270110',
    projectId: 'nutmeg-9414e',
    databaseURL: 'https://nutmeg-9414e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutmeg-9414e.appspot.com',
    iosClientId: '835265270110-4a5neh5o5eie13l2vm05uq0a5vjipaco.apps.googleusercontent.com',
    iosBundleId: 'com.autobonics.hydropodHydroponics',
  );
}
